### ISSUE TITLE
Setting output delay on line in

### ISSUE THREAD

**Issue by koshisan** [hklages/node-red-contrib-sonos-plus#159]
I noticed that currently the option to set the output delay on the line in doesn't seem to be implemented. Does Sonos not expose it through the API? Unfortunately I have a setup where I need to adjust the delay depending on the group configuration/input sources and I was hoping to do it automatically with node-red...

**Comment by hklages** [comment]
Hi. 
I am able to see this option in the Android app but can not find any corresponding item in the API. But as it is in the app there should be an api call or property.  You can have a look here: [documentation](https://svrooij.io/sonos-api-docs/services/audio-in.html)

Do you know Wireshark or any other software to get the network traffic and figure out the api call?

**Comment by koshisan** [comment]
Odd, because even the line level settings are documented...

The feature itself is described here: https://en.community.sonos.com/announcements-228985/sonos-version-10-6-2-brings-line-in-delay-settings-6836037

I tried running a packet capture, but since the app runs on android this isn't easy... I somehow managed, but it seems that the relevant part is not transmitted by http to port 1400. I could see the post requests of all my settings/activities in the app, _expcept_ for the audio delay configuration... However, there was additional encrypted traffic, so my guess is the app might do something undocumented here? It's either that or my packet capture missed the relevant parts (I am not 100% certain, because after restarting the sonos app I was getting no connection at all).

**Comment by hklages** [comment]
Thanks for running the packet capture. Yes - there are some encrypted "commands".
I need the "unencrypted UPNP" command.

There is no official documentation. The above mentioned documentation is compiled from several commands such as
[Audio In](192.168.178.37:1400/xml/AudioIn1.xml)

I opened a ticket at [node-sonos-ts](https://github.com/svrooij/node-sonos-ts/issues/139) - hopefully Stephan has a good idea.

**Comment by svrooij** [comment]
Personally I'm still on the S1 version (because of some old players), I don't see that option in my desktop controller. And I have no network capturing for my phone setup at the moment.

I just did a refresh of all the UPNP endpoints https://github.com/svrooij/sonos-api-docs/commit/5422c2a13f7200179c7a5c8c4ec9df3e35a35376 but that didn't change anything.

There are 2 options left:
1. Sonos implemented this delay feature in the rest api and not in UPNP (which means we are out of luck), see [this tweet](https://twitter.com/balloob/status/1416082681138356232?s=20) for more info on the subject.
2. This is a S2 only feature.

## Sonos S2 discovery files

Currently all the libraries that use the [generator](https://svrooij.io/sonos-api-docs/) only support all the features from the S1 system (because that is the system I have). I can use some help from someone with an S2 system to generate the required files (they are probably the same, but hopefully they support this new functionality). 

To check the last option, could you help me get the right discovery files?
1. Fork [this](https://github.com/svrooij/sonos-api-docs) library
2. Clone the library to your computer
3. open a command promth
4. go to the folder where you cloned the repo
5. enter `cd generator\sonos-docs` and press enter.
6. Execute `npm install`
7. run the following command for every model you have `.\bin\run services [ip]`
8. after this is done, you folder should have some changes.
9. Send the changes to github `git add .` then `git commit -m "chore: S2 discovery files"` and last `git push origin main`

What this does is generate a [discovery file](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs/data) for those models.

If you could generate these files, and share the url to your fork, I can have look and see if these actions are supported anywhere. That will also add them to node-sonos-ts eventually, because that library is mostly generated form these discovery files.

## Personal data

The above steps do query your local devices, but there is **NO** personal data (like devices serials) stored or transmitted anywhere. You can check the code of the generator, or the existing discovery files.

**Comment by koshisan** [comment]
@svrooij Thank you for the excellent guide! I am not a developer but thanks to the detailed instructions I was able to complete the process. The files are here: https://github.com/koshisan/sonos-api-docs/tree/main/generator/sonos-docs/data

However, as far as I can tell by skipping through them and the results of the earlier packetdumps, I am almost certain that the functionality is implemented through rest. 

Thanks to the excellent work of the community in reverse engineering the api and the integration in many projects I always thought that the Sonos api was open... Lesson learned: You need to check twice before buying...

**Comment by svrooij** [comment]
Your assumption was correct @koshisan, Sonos didn't implement this delay in the old UPNP api, but as a result of your work I did improve the documentation. All services like [AudioIn](https://svrooij.io/sonos-api-docs/services/audio-in.html) now have better model descriptions and show the version number where these services are coming from.

I cannot find the specified command in the [Cloud Control API](https://developer.sonos.com/reference/control-api/) so my guess it that this part is hidden in the local rest api (which runs at port `1433` and is https with a certificate from sonos). So one cannot see that traffic.

@hklages My suggestion is to close this issue with a label `No public API` that way you will eventually end up with a list of features you would like someone at Sonos will hopefully fix one day.
