### ISSUE TITLE
Q: Control sublevel, toggle nightmode and speech enhancement?

### ISSUE THREAD

**Issue by phralh** [hklages/node-red-contrib-sonos-plus#18]
Hi, 

Is it possible to control level for sub?
Is it possible to toogle nightmode and speech enhancement on playbar and sonos beam?

Would love to see these features so I can eliminate those steps in sonos official app.

Great work!

**Comment by hklages** [comment]
Hi. 
Control sub level - i have to further explore the available APIs. Will take some time. 
What do you mean with night mode / speech enhancement? On my Beam I am not able to find it. 
night mode = switch of LED light? That you can do with set_led.

**Comment by phralh** [comment]
Hi, 

Attached a screenshot of iOS app that shows night mode and speech enhancement. These might just be equalizer tweaks?

![122177FC-D451-4DB6-8973-ADD565150B83](https://user-images.githubusercontent.com/6092689/70792970-a0502f00-1d9a-11ea-9306-fae01521222c.jpeg)

Sub level control would be nice! :)

**Comment by hklages** [comment]
Ahhh I see. It's for the TV mode. None (night mode, text mode, sub control) are in the library node- Sonos (that's the base for this package). So I have to explore how to implement it.

**Comment by hklages** [comment]
Hi, I have just published 1.1.0. In Get Status node, there is now a command `get_eq`. Available topics are NightMode, DialogLevel (aka Speech Enhancement), SubGain (aka Level of sub). 

Please check whether you are able to get the current status of you system with these commands. 
NightMode 1 means on, DialogLevel 1 means Speech Enhancement on.  0 means off :-)

Especially I am interested to get the result from SubGain. It seems to be and "adjustment" and so that the value can also be negative. Lets see. 

If that works for you the set_eq will follow soon.

**Comment by phralh** [comment]
Gave it a spin and topics NightMode and DialogLevel work as expected. They both return the correct status as set in the sonos iOS app. 

SubGain returns values between -15 and 15. This corresponds to the available values to be set in the sublevel slider in the iOS app. It might be wise to limit set_eq value accordingly?

Appreciate your time and effort! :)

**Comment by hklages** [comment]
I just publish 1.2.0 - that includes seteq for NightMode, DialogLevel (aka speech enhancement) and SubLevel. The last I could not test  - hope it works. 
I changed the ouput of get_eq. It should now provide On/Off to have the same as in set_eq command.

Does it work for you?

**Comment by phralh** [comment]
Finally got a chance to try it out. All works out fine, including SubGain.

Great work, thanks! :)

**Comment by hklages** [comment]
Thanks for testing and providing feedback!

OK. Then I close this issue.
