### ISSUE TITLE
Request for Master/Slave and Name of Players in Group

### ISSUE THREAD

**Issue by Missenberger79** [hklages/node-red-contrib-sonos-plus#22]
Hi,

Can you Add or is it possible to have an ID for the Status if the Player in a Group as Master or Slave.

In the GroupInformation in get_Basic I have the value CurrentZonePlayerUUIDsInGroup. 
here I only see the Sonos UUID but not the real text. is it here possible to write the name like Kitchen,.... who is in the Group?

**Comment by hklages** [comment]
part 1: master / slave: 
You can use `get_basics`  / node "Get Status" and then use the standard switch node. 

![group-master-slave](https://user-images.githubusercontent.com/17273119/72442084-23a2dd00-37ac-11ea-8993-f4008660ee6f.png)

**Comment by hklages** [comment]
Subtopic 2: Names instead of the RINCON_*
Easiest is to create a global variable `playerMap` containing your mapping. You can do that with an inject node, change node and use the JSON format. (see picutre JSON).

![JSON PlayerMap](https://user-images.githubusercontent.com/17273119/72442874-96608800-37ad-11ea-9b35-fa02b5f501db.png)

Then use again `get_basics` with node "Get Status" and send the output to a function node with code: `
let idList = msg.group.CurrentZonePlayerUUIDsInGroup;
const map = global.get('playerMap');

for (let index = 0; index < map.length; index++) {
    idList = idList.replace(map[index].id, map[index].name);
}
msg.nameList = idList;
return msg;`

**Comment by hklages** [comment]
Does that solve your issue? 

For subtopic 2: 
Instead of a global variable, you can also create a subflow to create the array on the fly. In the subflow you have to inject get_basics, get_properties for each of your player and "merge" the data to a map (similiar to the global variabel) what you then can use.

**Comment by Rolf-M** [comment]
Hi Henning,
I'll pick up this one and not open up a new topic, as my suggestion is somehow related.
I've been contributing to the original node-red-contrib-sonos, even though my javascript skills are more than limited. I would suggest to move over to  svrooij/node-sonos-ts since this guy was one of the big contributors to node-sonos, but saw the limitations especially with grouping and so on. He made a lot of improvements for example logical devices, that will point instructions that have to go to the group coordinator directly there. I think you should look at it, as This might make a lot of things easier. (Except for you, having the work..) By the way, thanks for taking up the project, I was a little angry as this node-red-contrib-better-sonos came out, as it was mostly a copy, but you have done a great job, getting it further, thanks!
Regards, Rolf

**Comment by hklages** [comment]
I have just published 1.1.0. There is a new command: get_groups in Get Status Node. It outputs the msg.role (eg master, client, independent) and also an array with all groups and all members ins groups. There you can also find the names of the members.

**Comment by hklages** [comment]
@Rolf-M: I suggest that we discuss that off line via email: nrcsplus@gmail.com
Best regards, Henning

**Comment by Missenberger79** [comment]
the msg.role function works fine. But for me all of the Array is to difficult to pick the information what I need out. 

For me it will much easier to have f.e. msg.speakerInGroup with the value Bad, WC, Schlafzimmer. Where the first value in the string is the master. 

a second or additional useful information could be if msg.role = "Client" there is a msg.master = Name of the speaker. With this information I can write a Function to solve the problem to control a slave player via my knx-switch from each room.

**Comment by hklages** [comment]
Hi. I just published 2.1.2 and fixed a bug for get_groups. 
I took the chance and added: 
msg.coordinatorName, msg.coorinatorUuid, msg.memberNames (unsorted array)

Please notice that there are roles: coordinator, client and independent. That changed from 2.0.0.

With that I close this topic.

**Comment by Missenberger79** [comment]
Perfect. Thanks

Von meinem iPhone gesendet

**Comment by hklages** [comment]
@Rolf-M See the new event node at : [sonos-events](https://www.npmjs.com/package/node-red-contrib-sonos-events)

As you did suggest: based on nodes-sonos-ts
