### ISSUE TITLE
If no playlist exists in My Sonos, the "My Sonos" node will fail

### ISSUE THREAD

**Issue by thomasklingbeil** [hklages/node-red-contrib-sonos-plus#49]
The issue arises, when there are empty categories in My Sonos. After I added items there, the node worked as expected.

```
"get My Sonos items: Cannot read property 'length' of undefined :: Details: 
{"stack":"TypeError: Cannot read property 'length' of undefined\n at Object.parseSonosPlaylistsResult (/data/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:942:35)\n at
<anonymous>\n at 
process._tickCallback (internal/process/next_tick.js:189:7)",
"message":"Cannot read property 'length' of undefined"}"
```

**Comment by tsprivate** [comment]
I have the same issue.  What missing items did you add ... as workaround ?

my error below

`get My Sonos items: Cannot read property 'length' of undefined :: Details: {"stack":"TypeError: Cannot read property 'length' of undefined\n    at Object.parseSonosPlaylistsResult (/home/pi/.node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:942:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.getAllSonosPlaylists (/home/pi/.node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:644:32)\n    at async getAllMySonosItemsV2 (/home/pi/.node-red/node_modules/node-red-contrib-sonos-plus/src/Sonos-Commands.js:625:32)","message":"Cannot read property 'length' of undefined"}`

**Comment by thomasklingbeil** [comment]
I have added

- 1 album
- 1 track
- 1 playlist
- 1 radio station

Now it works.

**Comment by hklages** [comment]
In the Sonos app: go to the queue window, use the 3 vertical dot menue, save. That will create a Sonos playlist and should solve the issue. Alternative you can use the save.queue command in Univeral node.

I will send a fix today.

**Comment by tsprivate** [comment]
Thx for the help. I just added a single MP3 file to the playlist and it works now for me!

Is there a reason why 'Universal Node' cannot cover "My Sonos Node" features?

**Comment by hklages** [comment]
I just published 3.1.2. That should solve that issue. Please check. 

@tsprivate:  "My Sonos" is more or less a "bookmarking system". So it is different to all other stuff.  I wanted to create some awareness for the My Sonos feature in the Sonos app. I like it. It is very powerful and helps me to support Spotify, Napster, Deezer, ... without struggling with the different meta data, uri syntax.  I plan to provide search filters and will improve podcasts, radio show, ... 

During the next week "Manage Radio", "Manage Queue", most likely also "Get Status" and perhaps "Control player" will be transferred either to My Sonos oder Universal. 

Then I will re check whether My Sonos is still necessary. 
Your opinion?

**Comment by tsprivate** [comment]
I really like your Universal-Node and have now added the My-Sonos-Node just for reading/starting the playlist. I prefer single nodes with a good command structure (as you have started to do with the Universal node).

I just did my "Radio-Flow" with your Universal-Node and it works great.
`[{"id":"1d92b214.0a31ee","type":"debug","z":"a1390b9f.672798","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":330,"y":3200,"wires":[]},{"id":"279890ff.998b9","type":"change","z":"a1390b9f.672798","name":"state","rules":[{"t":"set","p":"payload","pt":"msg","to":"get.state","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":250,"y":2980,"wires":[["60651564.105eec","4e7a1a56.fe0344"]]},{"id":"f65b3d46.42fca","type":"inject","z":"a1390b9f.672798","name":"chevk","topic":"","payload":"","payloadType":"date","repeat":"10","crontab":"","once":true,"onceDelay":0.1,"x":120,"y":2980,"wires":[["279890ff.998b9"]]},{"id":"c54722d1.024b5","type":"sonos-universal","z":"a1390b9f.672798","confignode":"3ff0dd25.a83542","name":"Study","x":730,"y":2880,"wires":[["769be73f.8c1828"]]},{"id":"e71ed7f9.eaf108","type":"change","z":"a1390b9f.672798","name":"track","rules":[{"t":"set","p":"payload","pt":"msg","to":"get.trackplus","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":250,"y":3040,"wires":[["4e7a1a56.fe0344"]]},{"id":"60651564.105eec","type":"delay","z":"a1390b9f.672798","name":"","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":120,"y":3040,"wires":[["e71ed7f9.eaf108"]]},{"id":"769be73f.8c1828","type":"switch","z":"a1390b9f.672798","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"get.trackplus","vt":"str"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":910,"y":2880,"wires":[["aa14ea43.a306f8"],["5a034edd.33bdf","226aed8.b2b6412","2d097c7c.0a2df4","a4ee975d.41c998"]]},{"id":"4e7a1a56.fe0344","type":"switch","z":"a1390b9f.672798","name":"","property":"Sonos.Radio.Room","propertyType":"global","rules":[{"t":"eq","v":"Study","vt":"str"},{"t":"eq","v":"Kitchen","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":590,"y":2900,"wires":[["c54722d1.024b5"],["c1af574.18ab2a8"]]},{"id":"c1af574.18ab2a8","type":"sonos-universal","z":"a1390b9f.672798","confignode":"a1d81412.02c198","name":"Kitchen","x":740,"y":2920,"wires":[["769be73f.8c1828"]]},{"id":"8188a744.aec1f8","type":"ui_switch","z":"a1390b9f.672798","name":"","label":"Radio {{msg.payload}}","tooltip":"","group":"f96597f7.295c68","order":4,"width":2,"height":1,"passthru":false,"decouple":"true","topic":"","style":"","onvalue":"play","onvalueType":"str","onicon":"fa-play","oncolor":"white","offvalue":"stop","offvalueType":"str","officon":"fa-pause","offcolor":"red","x":250,"y":2760,"wires":[["561552a5.16035c"]]},{"id":"8fbf92b8.91464","type":"ui_switch","z":"a1390b9f.672798","name":"","label":"Mute {{msg.payload}}","tooltip":"","group":"f96597f7.295c68","order":5,"width":2,"height":1,"passthru":false,"decouple":"true","topic":"","style":"","onvalue":"On","onvalueType":"str","onicon":"volume_off","oncolor":"red","offvalue":"Off","offvalueType":"str","officon":"volume_up","offcolor":"white","x":250,"y":2900,"wires":[["c0af8199.0a992"]]},{"id":"4213bf1d.7221e","type":"link in","z":"a1390b9f.672798","name":"Rsdio-Mute","links":["3bd0f920.d19a66"],"x":95,"y":2900,"wires":[["8fbf92b8.91464"]]},{"id":"ce873618.c1b148","type":"link in","z":"a1390b9f.672798","name":"Rsdio-Play","links":["61d485df.ab411c","45f08adc.4f5d34","24ee89e0.6b0576"],"x":95,"y":2760,"wires":[["8188a744.aec1f8"]]},{"id":"ac2e15da.5e9af8","type":"ui_dropdown","z":"a1390b9f.672798","name":"","label":"Station","tooltip":"","place":"Select option","group":"f96597f7.295c68","order":2,"width":0,"height":0,"passthru":true,"options":[{"label":"Radio Off","value":"stop","type":"str"},{"label":"SWR3","value":"s24896","type":"str"},{"label":"Nova 96.9","value":"s17115","type":"str"}],"payload":"","topic":"","x":130,"y":2840,"wires":[["4501a3b5.f304ac"]]},{"id":"696c7b2a.702554","type":"change","z":"a1390b9f.672798","name":"Nova","rules":[{"t":"set","p":"topic","pt":"msg","to":"payload","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"play.tunein","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":390,"y":2860,"wires":[["4e7a1a56.fe0344"]]},{"id":"703ef5b3.6c92ac","type":"change","z":"a1390b9f.672798","name":"play","rules":[{"t":"set","p":"payload","pt":"msg","to":"play","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1270,"y":2960,"wires":[["45f08adc.4f5d34","3a8bf642.d8574a"]]},{"id":"5804cd81.442ed4","type":"change","z":"a1390b9f.672798","name":"stop","rules":[{"t":"set","p":"payload","pt":"msg","to":"stop","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1270,"y":3000,"wires":[["45f08adc.4f5d34","3a8bf642.d8574a"]]},{"id":"45f08adc.4f5d34","type":"link out","z":"a1390b9f.672798","name":"","links":["ce873618.c1b148"],"x":1395,"y":2960,"wires":[]},{"id":"5a034edd.33bdf","type":"switch","z":"a1390b9f.672798","name":"Play?","property":"payload.playbackstate","propertyType":"msg","rules":[{"t":"eq","v":"playing","vt":"str"},{"t":"eq","v":"stopped","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":1090,"y":2980,"wires":[["703ef5b3.6c92ac"],["5804cd81.442ed4"]]},{"id":"226aed8.b2b6412","type":"switch","z":"a1390b9f.672798","name":"Mute?","property":"payload.muteState","propertyType":"msg","rules":[{"t":"eq","v":"Off","vt":"str"},{"t":"eq","v":"On","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":1090,"y":3060,"wires":[["206a940c.64e30c"],["8bbc8d54.5590b"]]},{"id":"206a940c.64e30c","type":"change","z":"a1390b9f.672798","name":"unmute","rules":[{"t":"set","p":"payload","pt":"msg","to":"Off","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1280,"y":3040,"wires":[["3bd0f920.d19a66","2cc2f8d6.3e5098"]]},{"id":"8bbc8d54.5590b","type":"change","z":"a1390b9f.672798","name":"mute","rules":[{"t":"set","p":"payload","pt":"msg","to":"On","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1270,"y":3080,"wires":[["3bd0f920.d19a66","2cc2f8d6.3e5098"]]},{"id":"3bd0f920.d19a66","type":"link out","z":"a1390b9f.672798","name":"","links":["4213bf1d.7221e"],"x":1395,"y":3040,"wires":[]},{"id":"dccb2ab9.139878","type":"link in","z":"a1390b9f.672798","name":"Radio-Volume","links":["dbe3b797.406d58"],"x":95,"y":3080,"wires":[["f123a.bd9cadc68"]]},{"id":"f123a.bd9cadc68","type":"change","z":"a1390b9f.672798","name":"track","rules":[{"t":"set","p":"topic","pt":"msg","to":"payload","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"player.set.volume","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":250,"y":3080,"wires":[["4e7a1a56.fe0344"]]},{"id":"2d097c7c.0a2df4","type":"change","z":"a1390b9f.672798","name":"vol","rules":[{"t":"move","p":"payload.volume","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1090,"y":3140,"wires":[["f7f2c89f.7ecb48"]]},{"id":"f7f2c89f.7ecb48","type":"rbe","z":"a1390b9f.672798","name":"","func":"rbe","gap":"","start":"","inout":"out","property":"payload","x":1270,"y":3140,"wires":[["92d4b440.241ab8"]]},{"id":"92d4b440.241ab8","type":"link out","z":"a1390b9f.672798","name":"","links":["d516985d.bd2068"],"x":1395,"y":3140,"wires":[]},{"id":"2cc2f8d6.3e5098","type":"debug","z":"a1390b9f.672798","name":"mute","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1410,"y":3080,"wires":[]},{"id":"3a8bf642.d8574a","type":"debug","z":"a1390b9f.672798","name":"play","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1430,"y":3000,"wires":[]},{"id":"c0af8199.0a992","type":"change","z":"a1390b9f.672798","name":"Nova","rules":[{"t":"set","p":"topic","pt":"msg","to":"payload","tot":"msg"},{"t":"set","p":"payload","pt":"msg","to":"set.mutestate","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":390,"y":2900,"wires":[["4e7a1a56.fe0344"]]},{"id":"4501a3b5.f304ac","type":"switch","z":"a1390b9f.672798","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"stop","vt":"str"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":250,"y":2840,"wires":[["dd71b47.8d5e148"],["696c7b2a.702554"]]},{"id":"dd71b47.8d5e148","type":"change","z":"a1390b9f.672798","name":"stop","rules":[{"t":"set","p":"payload","pt":"msg","to":"stop","tot":"str"},{"t":"delete","p":"topic","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":390,"y":2820,"wires":[["4e7a1a56.fe0344"]]},{"id":"561552a5.16035c","type":"switch","z":"a1390b9f.672798","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"stop","vt":"str"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":390,"y":2760,"wires":[["ac2e15da.5e9af8"],["4e7a1a56.fe0344"]]},{"id":"5a26b23b.3e98bc","type":"change","z":"a1390b9f.672798","name":"","rules":[{"t":"set","p":"url","pt":"msg","to":"trackData.albumArtURL","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":350,"y":3320,"wires":[["1e9c71a6.49582e"]]},{"id":"1e9c71a6.49582e","type":"rbe","z":"a1390b9f.672798","name":"","func":"rbe","gap":"","start":"","inout":"out","property":"url","x":520,"y":3320,"wires":[["aedde84c.e226c8"]]},{"id":"aedde84c.e226c8","type":"http request","z":"a1390b9f.672798","name":"","method":"GET","ret":"bin","paytoqs":false,"url":"","tls":"","persist":true,"proxy":"","authType":"","x":670,"y":3320,"wires":[["95593c4a.9ca21"]]},{"id":"95593c4a.9ca21","type":"base64","z":"a1390b9f.672798","name":"Encode","x":860,"y":3320,"wires":[["c5be69fc.af81c8","7d6a505b.9cf1"]]},{"id":"c5be69fc.af81c8","type":"ui_template","z":"a1390b9f.672798","group":"f96597f7.295c68","name":"Display image","order":11,"width":"12","height":"12","format":"<img width=\"100\"  alt=\"mjpeg test...\" src=\"data:image/jpg;base64,{{msg.payload}}\" />\n","storeOutMessages":true,"fwdInMessages":true,"resendOnRefresh":false,"templateScope":"local","x":1060,"y":3320,"wires":[[]]},{"id":"7d6a505b.9cf1","type":"ui_text","z":"a1390b9f.672798","group":"4c691e5e.cc3e","order":2,"width":8,"height":6,"name":"","label":"{{msg.session.title}}","format":"{{msg.session.summary}}","layout":"col-center","x":1027.6354484558105,"y":3349.395839691162,"wires":[]},{"id":"f5a0216b.2f172","type":"link in","z":"a1390b9f.672798","name":"Radio-Track-Update","links":["aa14ea43.a306f8"],"x":95,"y":3240,"wires":[["6580fd68.0d4954","1d92b214.0a31ee","7bd1ed94.a92694"]]},{"id":"6580fd68.0d4954","type":"change","z":"a1390b9f.672798","name":"get.state","rules":[{"t":"set","p":"Radio.Artist","pt":"global","to":"artist","tot":"msg"},{"t":"set","p":"Radio.Titile","pt":"global","to":"title","tot":"msg"},{"t":"set","p":"Radio.Pos","pt":"msg","to":"positionData.RelTime","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":340,"y":3240,"wires":[["afba347f.8586b8","ec8ba44d.758518","f675096a.92fce8","bb86380e.f6d5d8"]]},{"id":"afba347f.8586b8","type":"ui_text","z":"a1390b9f.672798","group":"f96597f7.295c68","order":7,"width":5,"height":1,"name":"","label":"Time:  ","format":"{{msg.positionData.RelTime}}","layout":"row-left","x":510,"y":3280,"wires":[]},{"id":"ec8ba44d.758518","type":"string","z":"a1390b9f.672798","name":"30","methods":[{"name":"left","params":[{"type":"num","value":"30"}]}],"prop":"title","propout":"title","object":"msg","objectout":"msg","x":510,"y":3160,"wires":[["565ba899.f3b648"]]},{"id":"f675096a.92fce8","type":"string","z":"a1390b9f.672798","name":"30","methods":[{"name":"left","params":[{"type":"num","value":"30"}]}],"prop":"artist","propout":"title","object":"msg","objectout":"msg","x":510,"y":3200,"wires":[["f72688ae.19cc28"]]},{"id":"565ba899.f3b648","type":"ui_text","z":"a1390b9f.672798","group":"f96597f7.295c68","order":10,"width":0,"height":0,"name":"","label":"Title:  ","format":"{{msg.title}}","layout":"row-left","x":630,"y":3160,"wires":[]},{"id":"f72688ae.19cc28","type":"ui_text","z":"a1390b9f.672798","group":"f96597f7.295c68","order":9,"width":0,"height":0,"name":"","label":"Artist:  ","format":"{{msg.artist}}","layout":"row-left","x":630,"y":3200,"wires":[]},{"id":"aa14ea43.a306f8","type":"link out","z":"a1390b9f.672798","name":"","links":["f5a0216b.2f172"],"x":1055,"y":2860,"wires":[]},{"id":"a4ee975d.41c998","type":"debug","z":"a1390b9f.672798","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1070,"y":2900,"wires":[]},{"id":"b26d5a9c.2ba408","type":"ui_text","z":"a1390b9f.672798","group":"f96597f7.295c68","order":10,"width":0,"height":0,"name":"","label":"Album:  ","format":"{{msg.trackData.album}}","layout":"row-left","x":630,"y":3240,"wires":[]},{"id":"bb86380e.f6d5d8","type":"string","z":"a1390b9f.672798","name":"30","methods":[{"name":"left","params":[{"type":"num","value":"30"}]}],"prop":"trackData.album","propout":"title","object":"msg","objectout":"msg","x":510,"y":3240,"wires":[["b26d5a9c.2ba408"]]},{"id":"7bd1ed94.a92694","type":"switch","z":"a1390b9f.672798","name":"","property":"trackData.albumArtURL","propertyType":"msg","rules":[{"t":"nnull"}],"checkall":"true","repair":false,"outputs":1,"x":210,"y":3320,"wires":[["5a26b23b.3e98bc"]]},{"id":"3ff0dd25.a83542","type":"sonos-config","z":"","name":"Study","serialnum":"78-28-CA-23-EA-CE:E","ipaddress":"192.168.1.223"},{"id":"a1d81412.02c198","type":"sonos-config","z":"","name":"Kitchen","serialnum":"78-28-CA-23-EB-84:9","ipaddress":"192.168.1.220"},{"id":"f96597f7.295c68","type":"ui_group","z":"","name":"Radio","tab":"457f7667.10a928","order":2,"disp":true,"width":"12","collapse":true},{"id":"4c691e5e.cc3e","type":"ui_group","z":"","name":"PLEX - Living","tab":"fb7b1d26.ba726","order":3,"disp":true,"width":8,"collapse":true},{"id":"457f7667.10a928","type":"ui_tab","z":"","name":"Sonos","icon":"fa-headphones","order":7,"disabled":false,"hidden":false},{"id":"fb7b1d26.ba726","type":"ui_tab","z":"","name":"Kodi","icon":"fa-film","order":9,"disabled":false,"hidden":false}]`

Question:
- you can see in my Radio-flow that I use the AlbumUrl to display the Album-Image in my dashboard. Is it as well possible to get the same station-logo which SONOS is using in its app?
- Is it possible to get an Event-Trigger-Node (or within existing nodes) which is sending updates whenever there is a new event on Sonos (e.g. Volume-Change,Station-Change, Progress-Update,etc). This would avoid avoid a permanent repeat of "Get" requests to your nodes.
- For some strange reason you are using Topic and Payload the other-way-around than usual in Node-red. Was that intentional? I know a change a would break every existing flow .. but maybe you wanna consider it

Thanks for this node .. great work
Thomas

**Comment by hklages** [comment]
Just had a look at your flow and understand your point: 

> Is it possible to get an Event-Trigger-Node (or within existing nodes) which is sending updates whenever there is a new event on Sonos (e.g. Volume-Change,Station-Change, Progress-Update,etc). This would avoid avoid a permanent repeat of "Get" requests to your nodes.

There is [another node](https://flows.nodered.org/node/node-red-contrib-sonos-notify) which totally does not interfere with this node. We use the same library node-sonos. 

> For some strange reason you are using Topic and Payload the other-way-around than usual in Node-red. Was that intentional? I know a change a would break every existing flow .. but maybe you wanna consider it
I will open a new issue to discuss that. Let me know your ideas. 

> Please open a new issue for that. 

> Would it be possible to provide (optional) the Sonos-Name (e.g."Living","Kitchen",etc) to the Universal-Node so we don't need a "IF"-Node to select the correct target Sonos component

Please open a new issue. Does msg.playerName not help?

I close this issue My Sonos node fail as with the new release it should work.
