### ISSUE TITLE
Request:  Command/Topic in output of Universal_Node

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#62]
Hi,

Is it possible to have the original Command/Topic available in the output payload ? Otherwise it is not possible to identify what the original request was

![image](https://user-images.githubusercontent.com/41630517/81999586-e175a380-9698-11ea-8427-20ec1bbae9da.png)

Example:  Below payload is just saying OFF ... without knowing the command .. it was **Get_MuteState**
`{"_msgid":"1db406bf.7ac749","topic":"","payload":"Off"}`

Thanks for considering

**Comment by hklages** [comment]
Hi. 
I could add a property msg.cmd and set that property to the original command from msg.payload.
And in the next next next next release msg.cmd could replace the payload as input for commands and we can use payload as usual for on/off, ...

**Comment by tsprivate** [comment]
Yeah, I understand this will be a dramatic change. But based on the responses here it is just an inconvenience on my side and I have my workaround ;)

But the msg.cmd on output would be great

**Comment by hklages** [comment]
I am working on a new dialog for the Universal node. Hope to complete in 2 weeks.

1. selection
You can pick the command from the list of all commands. You can also pick "message" what means the command is retrieved from incoming message. 

2. payload for state, msg.cmd for command
You can use payload for the state on/off etc (former topic) and msg.cmd for the command. 

For all who prefer the old style there is a tic box to enable "compatibility" - payload for the command and msg.topic for states.

3. you can also specify the Sonos player name in the dialog instead of using msg.playerName = .xxx

**Comment by tsprivate** [comment]
I usually control my Sonos via the UI and keep my flows flexible by setting the necessary parameters outside the Universal-Node(or others).

A list of commands with details would be awesome (in the node. in the help or in the wiki)

**Comment by hklages** [comment]
Hi - did you find the list of commands? For Universal node it is [here](https://github.com/hklages/node-red-contrib-sonos-plus/wiki/A400.1-Universal-Node)

**Comment by tsprivate** [comment]
Yes, found it .. maybe you can provide a download link for the file itself (no PNG) in CSV or excel format
