### ISSUE TITLE
Control stereo pair with player.set-commands

### ISSUE THREAD

**Issue by floriandrott** [hklages/node-red-contrib-sonos-plus#74]
Hi guys,

I'm trying to control my stereo pair with the player.set-commands (like led and volume or join_group). Unfortunately it's not working ... only one speaker is affected by the command but not the whole stereo pair. The group-commands (like play/pause) are working fine.

Is there any way to control the stereo pair?

Thanks a lot,
Florian

**Comment by hklages** [comment]
Hi. Is it possible to change the led of both players in the SONOS app?
How do you change the volume of a stereopair? With right or left level?

**Comment by floriandrott** [comment]
Changing the led is possible within the SONOS app. If I use the universal node and change the "config node" with the coordinator speaker it's also working.

Changing the volume via the command player.set.volume is also not working ... just one speaker of the pair get changed. Coordinator is the right channel. 

Only if I pass the name via msg.playerName it's not working. Maybe because both speakers have the same name internally? I tried the command household.get.groups and the stereo pair is one group with an array of two speakers ... both with the same speaker name.

**Comment by hklages** [comment]
maybe I have to create a stereopair.set.led stereopair.set.volume etc. 
It will take a bit as I am on a trip and return end of next week. 

When creating a stereopair - one player is hidden and both have the same name. That makes it difficult - and I can not test it ( dont have 2 player one/3),

**Comment by floriandrott** [comment]
That would be very nice. Thank you!

If you would like we can test it together and we can use my stereo pair as the test candidate.

Here is the screenshot from the household command with the sonosNames .. and unfortunately both speakers have the same name within an stereo pair. 
![household groups](https://user-images.githubusercontent.com/53261305/85079318-d39acd00-b1c6-11ea-92b7-0718c21f4b45.jpg)

**Comment by dprokscha** [comment]
For universal node: I can confirm the behaviour **only** if I send commands to the **wrong IP address** of a stereo pair. As @hklages explained, after creating a stereo pair Sonos simply hides one of the players. You have to take care that you send the commands to the right player. To find the right IP address just try out, you only have two options 😉 

A stereo pair isn't a group and doesn't have a coordinator like a group - it's handled as a single player (which has a coordinator if its playing in a group). In your setup `household.get.groups` shows, that you have configured 3 groups and the stereo pair "Schlafzimmer" is the only player in its group. Also the other both groups only have one player.

I don't know if this really is a bug, because I know this behaviour from other Sonos bridges. The way how Sonos handles paired players (e.g. stereo pair or a TV setup) is special. It would be cool if the API returns more information like "Playername (L channel)", "Playername (R channel)" or a possibility to identify the visible player of a stereo pair. But even with this information you have to take care to configure the node the right way to reach the right player.

**Comment by floriandrott** [comment]
Thanks @dprokscha for the explanation. If I configure the player (stereo pair) directly in the node it's working.

My flow is a bit more generic and that's why I use the msg.playerName for the Universal node configuration. Here I can only set the playername but not the IP address. Maybe the fix would be that also the IP address can be transferred via the msg-object?

**Comment by hklages** [comment]
I will start work on it next week.

**Comment by hklages** [comment]
Hi. I just published 4.1. Its now similiar to the SONOS App. Hidden players are not any more shown and commands (set led, ...) will not work when using these players. You have to use the "non hidden" player to adjust volume, set led, etc. 

For the config node I did not change anything. I will revise that in the near future. There is need for more changes - for instance search for ip address in addition etc. and that has to be tested heavily.

Does it work for you?

**Comment by floriandrott** [comment]
Hi @hklages, thank you very much for your help! Now it works.

The players are listed as follows:
`{
  "_msgid": "7a3069a1.6041d8",
  "topic": "household.get.groups",
  "payload": [
    [
      {
        "urlHostname": "XX",
        "urlPort": 1400,
        "baseUrl": "http://XX:1400",
        "sonosName": "Schlafzimmer",
        "uuid": "RINCON_XX",
        "invisible": false
      }
    ],
    [
      {
        "urlHostname": "XX",
        "urlPort": 1400,
        "baseUrl": "http://XX:1400",
        "sonosName": "Wohnzimmer",
        "uuid": "RINCON_XX",
        "invisible": false
      }
    ],
    [
      {
        "urlHostname": "XX",
        "urlPort": 1400,
        "baseUrl": "http://10.0.7.21:1400",
        "sonosName": "Bad",
        "uuid": "RINCON_XX",
        "invisible": false
      }
    ]
  ],
  "nrcspCmd": "household.get.groups"
}`

'Set led' and so on are working. 'play.export' in combination with the MySonos-node seems not working with a upnp error 714 but maybe this is something within my network. I will check that one over the weekend. 

Thanks again for your help!

**Comment by hklages** [comment]
should be solve. Feel free to create a new issue, if not solved.
