### ISSUE TITLE
Challenges with GROUPS

### ISSUE THREAD

**Issue by tsprivate** [hklages/node-red-contrib-sonos-plus#87]
Hi there,

great progress you have achieved with your node. Well done... I really like it and use it everywhere

I'm now starting to manage the group in my automation as well via the UI but have a few challenges where I would need your help:

1) Creating Groups (player.join.group)
- I want to select the MASTER and SLAVE to select from a dropdown list (this is working already)
- I want to send the MASTER and SLAVE info to your Universal node
- I'm unable to send the MASTER information with an external message (**solved**)
==> just found the solution
=====> msg.topic = group.join.player
=====> msg.payload = Küche
=====> msg.playerName = Bad
- I can only send one SLAVE to the Universal node at a time (**Is there a way to send an array of SLAVES?**)

2) Leaving a Group (player.leave.group)
- I'm not able to send the MASTER information with an external message to the node (**solved**)
==> Same as above
- I can only remove 1 SLAVE player at a time (**Is there a way to send an array of SLAVES?**)
- Is there a way to clear a GROUP just by providing the MASTER?

### Versions and Infrastructure
**what system:**  Raspberry Pi 
**node-red-contrib-sonos-plus version:** 4.1.1
**Node-RED version:** 1.1.2

see: https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a

**Comment by hklages** [comment]
Hi. SONOS provides only 2 actions related to group management: AddMember, RemoveMember (and change coordinator, become coordinator, change coordinator) - and they only work on a single player!

What I can do is: 
household.separate.group: input any group member => will remove all players from group step by step and as a result all are stand alone players.

household.create.group: input of strings with names ==> will group all together with first name as coordinator step by step. 
(maybe as prereq remove at least coordinator from any group otherwise its members will belong to the new group automatically)

I will start my vacation Monday - so that could be released  end of September. 

You might be able to do the same in flows using` household.get.groups, player.join.group, player.leave.group`

**Comment by hklages** [comment]
4.2.0 is published with the above commands. You can define a group with `household.create.group` and state: "Küche,Bad,Wohnzimmer" - Küche will become the new coordinator. 
You can use that "create" command also for any changes. To add a player just submit ""Küche,Bad,Wohnzimmer,Büro" and the program will add Büro to that group.

I hope my algorithm for handling changes is smart and efficient - and close this topic. Feel free to open a new one in case of any issues.
