### ISSUE TITLE
Group multiple players

### ISSUE THREAD

**Issue by martinjuhasz** [hklages/node-red-contrib-sonos-plus#90]
### Description
Hey, i'm trying to add multiple sonos speakers into one group. somehow when i call the `player.join.group` multiple times in a row, it replaces one after another so that at any given time only two players are in one grp.
What is the correct way of grouping multiple speakers?

<img width="656" alt="Screenshot 2020-08-23 at 18 07 12" src="https://user-images.githubusercontent.com/204190/90983043-8e4e9f00-e56b-11ea-83a4-21062e2e741e.png">
This should add my three speakers together with my main one as the config node and the others two with calls to `player.join.group`.

### What node/command (topic)/state (payload)?
```
[{"id":"e7b46e5.659199","type":"sonos-manage-mysonos","z":"f57f2ef2.84554","confignode":"3981b863.b28838","compatibilityMode":false,"command":"mysonos.export.item","state":"Songs","stateType":"str","name":"","x":840,"y":2760,"wires":[["9a0b18ca.4f82c8"]]},{"id":"9a0b18ca.4f82c8","type":"sonos-universal","z":"f57f2ef2.84554","confignode":"3981b863.b28838","compatibilityMode":false,"command":"group.play.export","state":"","stateType":"str","name":"","x":1090,"y":2760,"wires":[[]]},{"id":"5969f068.730ab","type":"sonos-universal","z":"f57f2ef2.84554","confignode":"3981b863.b28838","compatibilityMode":false,"command":"player.join.group","state":"Küche","stateType":"str","name":"","x":520,"y":2720,"wires":[["9c831c4b.5ab65"]]},{"id":"9c831c4b.5ab65","type":"sonos-universal","z":"f57f2ef2.84554","confignode":"3981b863.b28838","compatibilityMode":false,"command":"player.join.group","state":"Arbeitszimmer","stateType":"str","name":"","x":520,"y":2820,"wires":[["e7b46e5.659199"]]},{"id":"e87f2df6.f75c7","type":"inject","z":"f57f2ef2.84554","name":"trigger","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":290,"y":2800,"wires":[["5969f068.730ab"]]},{"id":"3981b863.b28838","type":"sonos-config","z":"","name":"Sonos Wohnzimmer","serialnum":"48-A6-B8-B0-AD-EB:3","ipaddress":"10.0.20.20"}]
```
### Versions and Infrastructure
running the latest version of node-red and the node itself.

**Comment by hklages** [comment]
You mixed up the naming - reverse it and it will work. 

**What did you do:** 
In your first node player.join.group the 10.0.20.20 (Sonos Wohnzimmers) joins the group of "Küche". So you created a group with Küche + Wohnzimmer. 

Then the second play.join.goup adds 10.0.20.20 (Sonos Wohnzimmer) to "Arbeitszimmer" and leaves the former group with Küche. 

**Please do**
Assuming that the name of the SONOS players are "Wohnzimmer, Küche, Arbeitszimmer" and the corresponding configfiles are "Sonos Wohnzimmer, Sonos Küche, Sonos, Arbeitszimmer": 

First node: State Wohnzimmer, configfile: Sonos Küche
Second node: State Wohnzimmer, configfile : Sonos Arbeitszimmer.

Another option is to use msg.playerName Küche in first node and msg.playerName Arbeitszimmer instead of the config files. You can use Sonos Wohnzimmer as configfile as playerName overwrites configfile.

Does it work then? 
You can see the groups with `household.get.groups`

(I know - the documentation should be improved. Maybe in in October/November at rainy days :-)

**Comment by martinjuhasz** [comment]
Perfect that worked. Thank you.

Yeah, its a bit hard to get to know what all the config options are used for. Would be really nice to have a comprehensive documentation. I guess also for not having to answer the same questions all over again on the issue tracker.

Thank you for all your work on that node and the recent refactoring! Really liking it.

**Comment by hklages** [comment]
4.2.0 is published with new grouping commands. You can define a group with household.create.group and state: "Küche,Bad,Wohnzimmer" - Küche will become the new coordinator.
You can use that "create" command also for any changes. To add a player just submit ""Küche,Bad,Wohnzimmer,Büro" and the program will add Büro to that group.

I hope my algorithm for handling changes is smart and efficient - and close this topic. Feel free to open a new one in case of any issues.
