### ISSUE TITLE
group.play.tunein play error

### ISSUE THREAD

**Issue by thomasoggier** [hklages/node-red-contrib-sonos-plus#95]
Sometime when I try to start a tunein radio with the function "group: play tunein station" s71108,
I get this error msg -> "group.play.tunein:statusCode 500 & upnpError 701 :: Details: unknown error"
and the station is not played.
this error does not appear often but that's strange.
And some other time, my sonos begin with saying something strange in english before starting playing the radio.
![image](https://user-images.githubusercontent.com/64468458/93425677-c3c08100-f8ba-11ea-9ec6-e9835c03b893.png)

**Comment by hklages** [comment]
Yes - that's strange. Sonos returns the 701 what means "No such object". That does not help us. 

you may
a) add the station "Virgin Rock Alternative" to My Sonos and use the node "My Sonos" to launch the station instead of direct.
(How: In the SONOS App, use Search,  station, Virgin Rock Alternative" - either from Tune In or Sonos, Three Dots: Add Station to my Sonos)

 --- or 

b) add a catch node to catch that error and just submit the command again - best with a short delay (few seconds)

**Comment by thomasoggier** [comment]
Hi, thanks for your answer,
I've add mysonos and select another radio (I'm not at home now, so I can't change my sonos settings now).
So I've tried a lot of time to start the other radio with mysonos stream.item and it's look working (I've get no error wit 30 start)

That's strange that with te other module, it works fine, but only once per 50, it "crashed".
I've also add the catch module and get exacty le same error that before.

But thanks for your help, I will use the other module in futur.
